server.port=8000

# MySQL DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/university_registrar?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Enable JSON Logging Formatting
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
